query PostsAndPortfoliosQuery {
  posts {
    title
    slug
    description
    date
    id
    tags
    author {
      name
      image
      imageWidth
      imageHeight
    }
  }
  portfolios {
    title
    slug
    tags
    description
    date
    coverImage
    coverImageWidth
    coverImageHeight
  }
}
