query PostBySlugQuery($slug: String!) {
  post(where: { slug: $slug }) {
    title
    slug
    description
    date
    id
    tags
    author {
      name
      image
      imageWidth
      imageHeight
    }
  }
}
