query BlogItemBySlugQuery($slug: String!) {
  blogItem: post(where: { slug: $slug }) {
    title
    slug
    description
    date
    id
    tags
    content
    author {
      name
      image
      imageWidth
      imageHeight
    }
  }
}
